name: lighthouse format
description: エラー情報のjsonからmarkdownに変換する処理
inputs:
  json-file-path:
    description: lighthouseci実行時に生成されたファイルのパス
    required: true
outputs:
  result-md-file:
    description: markdownに変換したファイル
runs:
  using: node12
  main: index.js