name: deploy to s3
on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Install Dependencies
        run: yarn install
        
      - name: Build
        run: yarn prod
        
      - name: Deploy
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # TODO: terraform導入できたらデプロイ先を変える必要あり
        run: aws s3 cp --recursive --region ap-northeast-1 public s3://aws-intro-sample-upload-shoma
