name: Lighthouse CI
on: 
  pull_request: 


jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: yarn install

      - name: install Lighthouse cli and build
        run: |
          yarn add @lhci/cli@0.8.x
          yarn prod

      - name: run Lighthouse cli 
        run: yarn lhci autorun
        env: 
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: create comment
        run: |
          cat << EOF > comments
          1st
          2nd
          3rd
          EOF

      - name: post comment
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          URL: ${{ github.event.pull_request.html_url }}
        run: gh pr comment -F ./comments "${URL}"